# Meta Data for SEO

## Homepage
title = "Telos Kitchen"
titleSeparator = "-"
titleAddition = "Block producer candidate and development team"
description = "Block producer candidate and development team"

## Open Graph + Twitter Cards
images = ["teloskitchen-logo.png"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "teloskitchen-logo.png"
# schemaTwitter = "https://twitter.com/henkverlinde"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/teloskitchen"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
# footer = "(c) Telos Kitchen DAO LLC"

# Edit Page
docsRepo = "https://github.com/teloskitchen/telos.kitchen"
editPage = false
