name: build

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  push_to_registry:
    name: Push Docker image to Tekit Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Tekit Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.TEKIT_REGISTRY_USERNAME }}
          password: ${{ secrets.TEKIT_REGISTRY_PASSWORD }}
          registry: registry.tekit.io
          repository: dappdever/hancock-is
          tag_with_ref: true

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm test

      - name: Build production website
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: registry.tekit.io
          username: ${{ secrets.TEKIT_REGISTRY_USERNAME }}
          password: ${{ secrets.TEKIT_REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dappdever/hancock-is:latest