name: build

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm test

      - name: Build production website
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.tekit.io/hancock-web
          username: ${{ secrets.TEKIT_REGISTRY_USERNAME }}
          password: ${{ secrets.TEKIT_REGISTRY_PASSWORD }}
          registry: registry.tekit.io
          context: .
          tags: latest